### ISSUE TITLE
Epic 2 - User Story 1

### ISSUE THREAD

**Issue by OrbicCode** [SchoolOfCode/bc17-w4d2-project-triple-jam#3]
User Story: Implement functionality to GET all activities for a particular user

Description:

As Kenny, a busy front end engineer I need to be able to send a GET request with a user_id to the API to get a users activities so that I can make a nice simple dashboard that shows a user all of their activities.

As Norman, a Tech Lead working across lots of projects I need to be able to depend on conventions like: the response object always containing a key called data or error, or the status code being an accurate indication of the success/failure (and reason) of the request.

Acceptance Criteria:

Given I am a developer who has the Activity API running,
When I make a GET request to “http://localhost:3000/activities”

Then the the request should succeed, responding with the correct status code and an array of User Activity objects in the response body (response.data).

// response object

{
	data: [
		{ }, // activity object
		{ }, // activity object
		{ } // activity object
	]
}

// each activity object should look like

{
	"id": "54321234", // UUID
	"activity_submitted": "1719486190058", // simple Epoc timestamp (Date.now() in JS)
	"activity_type": "run", // choose some standard types
	"activity_duration": "30", // choose standard unit type (minutes probably)
}
```[tasklist]
### Tasks
- [x] Create activities.js file
- [x] Create an array of objects
- [x] Export json file
- [x] Import activity.js in index.js
- [x] Make a new GET request to URL “http://localhost:3000/activities”
- [x] Test it out (Postman and fetch request)
```
