### ISSUE TITLE
Epic 3 - User Story 1

### ISSUE THREAD

**Issue by OrbicCode** [SchoolOfCode/bc17-w4d2-project-triple-jam#5]
User Story: Implement functionality to PUT (update) an activity

Description:

As Kenny, a busy front end engineer I need to be able to send a PUT request with a JSON request body (the activity to update) to the API so that I can make a simple form that allows my user to edit an activity.

As Norman, a Tech Lead working across lots of projects I need to be able to depend on conventions like: the response object always containing a key called data or error, or the status code being an accurate indication of the success/failure (and reason) of the request.

Acceptance Criteria:

Given I am a developer who has the Activity API running,
When I make a PUT request to “http://localhost:3000/activities” with a request body containing a JSON object (updated activity),
Then the API should update the activity in the activities.json file that has a matching activity id,
Then the the request should succeed, responding with the correct status code and the activity object that I posted as the response body (response.data).
// request object - updated user activity that we send in the PUT request
{
    "id": "54321234", // id of an exisiting activity
    "activity_type": "cycle",
    "activity_duration": "60",
}
​
// save the newly updated activity in activities.JSON as 
​
[
    {}, // exisitng activity
    {}, // exisitng activity
    {
        "id": "54321234",
        "activity_submitted": "1719486190058", // Update time stmap or leave it the same
        "activity_type": "cycle",
        "activity_duration": "60",
    }
]

Given I am a developer who has made an invalid PUT request by specifying an id for a activity that does not exist,
When I inspect the API response,
Then the request should fail, responding with the correct status code and a clear error message (response.error).
```[tasklist]
### Tasks
- [x] create put request handler at /activities
- [x] create request body in postman
- [x] match id in request body to API id
- [x] create catch error 400
```
